c_compiler:             # [osx]
  - clang_bootstrap     # [osx]
cxx_compiler:           # [osx]
  - clang_bootstrap     # [osx]

c_compiler:            # [win]
  - vs2022             # [win]
cxx_compiler:          # [win]
  - vs2022             # [win]

c_compiler_version:
  - 19.1.7            # [osx]
cxx_compiler_version:
  - 19.1.7            # [osx]