c_compiler:          # [unix]
  - clang_bootstrap  # [osx]
  - gcc              # [linux]
cxx_compiler:        # [unix]
  - clang_bootstrap  # [osx]
  - gxx              # [linux]

c_compiler_version:     # [osx]
  - "*"                 # [osx]
cxx_compiler_version:   # [osx]
  - "*"                 # [osx]
