c_compiler:
  - clang_bootstrap  # [osx]
cxx_compiler:
  - clang_bootstrap  # [osx]
c_compiler_version:     # [osx]
  - "*"                 # [osx]
cxx_compiler_version:   # [osx]
  - "*"                 # [osx]
