{% set version = "17.0.6" %}

package:
  name: lld
  version: {{ version }}

source:
  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version.replace(".rc", "-rc") }}/llvm-project-{{ version.replace(".rc", "rc") }}.src.tar.xz
  sha256: 58a8818c60e6627064f312dbf46c02d9949956558340938b71cf731ad8bc0813
  patches:
    - patches/0001-point-header-inclusion-in-lld-MachO-CMakeLists.txt-t.patch

build:
  number: 0
  skip: True  # [linux and s390x]
  ignore_run_exports_from:
    # not actually needed on unix
    - libxml2  # [unix]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - llvmdev =={{ version }}              # [build_platform != target_platform]
    - patch       # [not win]
    - m2-patch    # [win]
  host:
    - libcxx {{ cxx_compiler_version }}    # [osx]
    - llvmdev =={{ version }}
    - llvm
    # these they are present in the host env anyway as run-deps of llvm
    # and will be picked up for the build by the default settings
    - libxml2       {{ libxml2 }}
    - zlib          {{ zlib }}
    - zstd          {{ zstd }}
  run:
    - {{ pin_compatible("libcxx", max_pin=None) }}  # [osx]
  run_constrained:
    - llvm =={{ version }}
  test:
    commands:
      - ld.lld --version  # [unix]
      - lld-link /?       # [win]

about:
  home: https://lld.llvm.org/
  license: Apache-2.0 WITH LLVM-exception
  license_file: lld/LICENSE.TXT
  license_family: Apache
  summary: The LLVM Linker
  dev_url: https://github.com/llvm/llvm-project/
  doc_url: https://llvm.org/docs/
  description: |
    LLD is a linker from the LLVM project that is a drop-in 
    replacement for system linkers and runs much faster than 
    them. It also provides features that are useful for 
    toolchain developers.

extra:
  skip-lints:
    # false positives, and a bit of a special case.
    - missing_tests
    - should_use_compilers
  recipe-maintainers:
    - isuruf
    - h-vetinari
