{% set version = "10.0.0" %}
{% set sha256 = "b9a0d7c576eeef05bc06d6e954938a01c5396cee1d1e985891e0b1cf16e3d708" %}

package:
  name: lld
  version: {{ version }}

source:
  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version }}/lld-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}
  patches:
    - cmake.diff

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake >=3.4.3
    - ninja    # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - llvmdev =={{ version }}
    - swig
    - llvm
  run_constrained:
    - llvm =={{ version }}

test:
  commands:
    - ld.lld --version  # [linux]
    - lld-link /?  # [win]

about:
  home: http://llvm.org/
  license: NCSA
  license_file: LICENSE.TXT
  summary: The LLVM Linker

extra:
  recipe-maintainers:
    - isuruf
