{% set version = "17.0.6" %}

package:
  name: lld
  version: {{ version }}

source:
  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version.replace(".rc", "-rc") }}/llvm-project-{{ version.replace(".rc", "rc") }}.src.tar.xz
  sha256: 58a8818c60e6627064f312dbf46c02d9949956558340938b71cf731ad8bc0813
  patches:
    - patches/0001-point-header-inclusion-in-lld-MachO-CMakeLists.txt-t.patch

build:
  number: 0
  skip: True  # [(win and vc<14) or (linux and s390x)]
  ignore_run_exports: # [not win]
    - libxml2         # [not win]
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - m2-patch    # [win]
    - make        # [not win]
    - ninja       # [win]
    - patch       # [not win]
  host:
    - libcxx {{ version }}  # [osx]
    - libxml2 {{ libxml2 }}
    - llvm {{ version }}
    - llvmdev {{ version }}
    - zlib {{ zlib }}
    - zstd {{ zstd }}
  run:
    - {{ pin_compatible("libcxx", max_pin=None) }}  # [osx]
  run_constrained:
    - llvm =={{ version }}

test:
  commands:
    - ld.lld --version  # [linux]
    - lld-link /?       # [win]

about:
  home: https://lld.llvm.org/
  license: Apache-2.0 WITH LLVM-exception
  license_family: Apache
  license_file: lld/LICENSE.TXT
  summary: The LLVM Linker
  description: |
    LLD is a linker from the LLVM project that is a drop-in replacement for system linkers and runs much faster than them. It also provides features that are useful for toolchain developers.
    The linker supports ELF (Unix), PE/COFF (Windows), Mach-O (macOS) and WebAssembly in descending order of completeness. Internally, LLD consists of several different linkers. The ELF port is the one that will be described in this document. The PE/COFF port is complete, including Windows debug info (PDB) support. The WebAssembly port is still a work in progress
  dev_url: https://github.com/llvm/llvm-project/
  doc_url: https://github.com/llvm/llvm-project/

extra:
  recipe-maintainers:
    - isuruf
    - katietz
    - h-vetinari
