{% set version = "14.0.6" %}

package:
  name: lld
  version: {{ version }}

source:
  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version.replace(".rc", "-rc") }}/llvm-project-{{ version.replace(".rc", "rc") }}.src.tar.xz
  sha256: 8b3cfd7bc695bd6cea0f37f53f0981f34f87496e79e2529874fd03a2f9dd3a8a
  patches:
    - patches/0001-point-header-inclusion-in-lld-MachO-CMakeLists.txt-t.patch

build:
  number: 0
  skip: True  # [win and vc<14]
  skip: Truea # [linux and s390x]
  ignore_run_exports: # [not win]
    - libxml2         # [not win]
requirements:
  build:
    - cmake >=3.4.3
    - ninja    # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make     # [not win]
    - patch       # [not win]
    - m2-patch    # [win]
  host:
    - llvmdev =={{ version }}
    - llvm
    - libxml2
    - zlib
    - libcxx  # [osx]
  run_constrained:
    - llvm =={{ version }}

test:
  commands:
    - ld.lld --version  # [linux]
    - lld-link /?  # [win]

about:
  home: https://lld.llvm.org/
  license: Apache-2.0 WITH LLVM-exception
  license_family: Apache
  license_file: lld/LICENSE.TXT
  summary: The LLVM Linker
  dev_url: https://github.com/llvm/llvm-project/
  doc_url: https://github.com/llvm/llvm-project/

extra:
  recipe-maintainers:
    - isuruf
    - katietz
    - h-vetinari
