{% set version = "8.0.0" %}
{% set sha256 = "9caec8ec922e32ffa130f0fb08e4c5a242d7e68ce757631e425e9eba2e1a6e37" %}

package:
  name: lld
  version: {{ version }}

source:
  fn: lld-{{ version }}.src.tar.xz
  url: http://releases.llvm.org/{{ version }}/lld-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake >=3.4.3
    - ninja    # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - llvmdev =={{ version }}
    - swig
  run_constrained:
    - llvmdev =={{ version }}

test:
  commands:
    - ld.lld --version  # [linux]
    - lld-link /?  # [win]

about:
  home: http://llvm.org/
  license: NCSA
  license_file: LICENSE.TXT
  summary: The LLVM Linker

extra:
  recipe-maintainers:
    - isuruf
