{% set version = "8.0.1" %}
{% set sha256 = "9fba1e94249bd7913e8a6c3aadcb308b76c8c3d83c5ce36c99c3f34d73873d88" %}

package:
  name: lld
  version: {{ version }}

source:
  fn: lld-{{ version }}.src.tar.xz
  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-{{ version }}/lld-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake >=3.4.3
    - ninja    # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - llvmdev =={{ version }}
    - swig
  run_constrained:
    - llvmdev =={{ version }}

test:
  commands:
    - ld.lld --version  # [linux]
    - lld-link /?  # [win]

about:
  home: http://llvm.org/
  license: NCSA
  license_file: LICENSE.TXT
  summary: The LLVM Linker

extra:
  recipe-maintainers:
    - isuruf
