travis:
  secure:
    BINSTAR_TOKEN: YcUpeM7NFVnsyAV5nIG7B7NN9WapbutDPPsh0MhfL8UNYQZ/m0CXkljhGDxWMx9mjcm4GYNx+GMlqGtwcGW99WolvbghHK36YIcRd3GSqOf08FxpRp8HJ+L7PDaWIuudalVAs50K00sJtKfFKOiBKmPkDF6lYkJNLQN+qDAmaNPjUZCZneVEGVKQrBi6RW7jgY0A2MzLnOGc3qol0SoVQnVWvMBmwZ9pZyKIaYaIZg0FtuxoBsXjfZToJwivGItA2J8G1GSXNIR4aQfBWPHNa9pNflzg6ZZ/OvdM9ub8vn9qctTqN2kEQiRBxc4pJyare5zc9xD9rNX+fZ+mSeQaniqFuu4rtqHjIF1Xqkl/9zyblRN8bSjID0i47q+3WP6GqiGaAyTBAz1A4DOt89loA2cl4fuxj0aeI8FCGsYmCxZKvYoqAiec+VXo3lh07jwTC7GVF6xCy8XpWPLh431efZNIFZf3X2ef64Z8TEExf0cZFqUjZPdMTsOc1dPnxS1lXISSAEntGazO1CM2AY5DX125V/SOYq+9H8l2rhqole+IxwzTsC80aDQSuZB2t250IbirWJZL4D2tRwOvXbEoEtywWNbh/T4oHHBSovMADoISbD7S7e0njIvDsQLtzmGl2gYnnd7C0MrA14xvrdzI6RT1AjJJkDLj7opN/5fY8OE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
